#pragma once
#include <age/vector/vector3.h>
#include <age/vehicle/transmission.h>
#include <age/vehicle/aero.h>
#include <age/vehicle/wheel.h>
#include <age/physics/phcollider.h>
#include <age/vehicle/nitro.h>
#include <age/vehicle/carSSTurbo.h>

class vehTransmission;
class vehWheel;

class vehCarSim {
public:
	void* m_Vtable;
	int dword_04;
	int dword_08;
	vehAero* m_Aero;
	void* m_Fluid;
	void* m_Engine;
	vehTransmission* m_Transmission;
	int m_NumWheels;
	vehWheel* m_WheelFront;
	int m_NumDrivetrains;
	void* m_Drivetrain;
	int m_NumAxles;
	void* m_Axle;
	int m_NumSuspensions;
	void* m_Suspension;
	int dword_3c;
	int dword_40;
	int dword_44;
	Vector3 dword_48;
	Vector3 m_ModelOffset;
	Vector3 m_CenterOfMass;
	phCollider* m_Collider;
	float m_Steer;
	float m_Throttle;
	float m_Brake;
	float m_Handbrake;
	float field_80;
	float field_84;
	float field_88;
	float field_8C;
	float field_90;
	float field_94;
	float field_98;
	float field_9C;
	float field_A0;
	float field_A4;
	float field_A8;
	float field_AC;
	float m_Speed;
	float field_B4;
	float m_Mass;
	Vector3 m_Size;
	Vector3 m_InertiaBox;
	float m_BoundFriction;
	float m_BoundElasticity;
	float m_BoundGravity;
	float m_AirGravity;
	int m_DrivetrainType;
	int dword_e8;
	vehWheel* m_Wheels[4];	
	int dword_fc;
	int dword_100;
	int dword_104;
	int dword_108;
	int dword_10c;
	int dword_110;
	int dword_114;
	int dword_118;
	int dword_11c;
	int dword_120;
	int dword_124;
	int dword_128;
	int dword_12c;
	int dword_130;
	int dword_134;
	int dword_138;
	int dword_13c;
	int dword_140;
	int dword_144;
	int dword_148;
	int dword_14c;
	int dword_150;
	int dword_154;
	int dword_158;
	int dword_15c;
	int dword_160;
	int dword_164;
	int dword_168;
	int dword_16c;
	int dword_170;
	int dword_174;
	int dword_178;
	int dword_17c;
	int dword_180;
	char field_184;
	bool m_BurnoutCharged;
	char field_186;
	char field_187;
	int dword_188;
	float m_BurnoutValue;
	float m_BurnoutIncreaseSpeed;
	float m_BurnoutDecreaseSpeed;
	float m_BurnoutDamageAmount;
	float m_BurnoutBoostSpeed;
	int m_BurnoutCharging;
	int dword_1a4;
	int dword_1a8;
	float m_SteeringLimit;
	float m_Airtime;
	float m_SomeBrake;
	int dword_1b8;
	int dword_1bc;
	int dword_1c0;
	int dword_1c4;
	int dword_1c8;
	int dword_1cc;
	vehNitro* m_Nitro;
	mcCarSSTurbo* m_SSTurbo;
	int dword_1d8;

public:
	int OnGround(); // Number of wheels on ground
};
