#pragma once
enum VEHICLE_TYPE {
	vp_escort   = 0,
	vp_civica   = 1,
	vp_jetta    = 2,
	vp_integraa = 3,
	vp_gto      = 4,
	vp_s2000    = 5,
	vp_cbr929a  = 6,
	vp_civicb   = 7,
	vp_rx7      = 8,
	vp_viper    = 9,
	vp_puma     = 10,
	vp_cosworth = 11,
	vp_m5       = 12,
	vp_elise    = 13,
	vp_golfa    = 14,
	vp_ducati   = 15,
	vp_clio     = 16,
	vp_vanquish = 17,
	vp_911      = 18,
	vp_lexus    = 19,
	vp_nissanz  = 20,
	vp_mr2      = 21,
	vp_supraa   = 22,
	vp_lancer   = 23,
	vp_yamaha   = 24,
	vp_suprab   = 25,
	vp_skylinea = 26,
	vp_saleen   = 27,
	vp_slf450x  = 28,
	vp_cop_l    = 29,
	vp_pariscop = 30,
	vp_tokyocop = 31,
};

enum RACE_TYPE {
	roam                     = 0,
	find_hook                = 1,
	hookman_cruise           = 2,
	follow                   = 3,
	cp_unordered             = 4,
	cp_unordered_time_local  = 5,
	cp_unordered_time_global = 6,
	cp_ordered               = 7,
	cp_ordered_time_local    = 8,
	cp_ordered_time_global   = 9,
	capture_the_flag         = 10,
	bomb_tag                 = 11,
	lose_the_cops            = 12,
	destroy                  = 13
};

enum CITY {
	losangeles  = 0,
	paris       = 1,
	tokyo       = 2,
	qualcomm    = 3,
	test2       = 4,
	testphysics = 5,
	stunt1      = 6,
	stunt2      = 7,
	stunt3      = 8,
	arena1      = 9,
	arena2      = 10,
	arena3      = 11,
	nocity      = 12
};